LMS7002M_PREFIX ?= $(PREFIX)
LMS7002M_LIB = $(LMS7002M_PREFIX)/lib/libLMS7002M.a
$(LMS7002M_LIB):
	$(RM) -r LMS7002M-driver/build
	mkdir -p LMS7002M-driver/build
	cmake -DCMAKE_INSTALL_PREFIX=$(LMS7002M_PREFIX) \
		  -DCMAKE_BUILD_TYPE=Debug \
		  -S LMS7002M-driver \
		  -B LMS7002M-driver/build
	$(MAKE) -C LMS7002M-driver/build install
LMS7002M-driver: $(LMS7002M_LIB)
clean-LMS7002M-driver:
	-$(MAKE) -C LMS7002M-driver/build clean
	$(RM) $(LMS7002M_LIB)
clean: clean-LMS7002M-driver
