//--------------------------------------------------------------------------------
// Auto-generated by LiteX (3959ca39) on 2022-08-17 22:16:42
//--------------------------------------------------------------------------------
#ifndef __GENERATED_SOC_H
#define __GENERATED_SOC_H
#define CONFIG_CLOCK_FREQUENCY 125000000
#define CONFIG_CPU_HAS_INTERRUPT
#define CONFIG_CPU_RESET_ADDR 0
#define CONFIG_CPU_TYPE_VEXRISCV
#define CONFIG_CPU_VARIANT_MINIMAL
#define CONFIG_CPU_HUMAN_NAME "VexRiscv_Min"
#define CONFIG_CPU_NOP "nop"
#define CONFIG_MAIN_RAM_INIT 1
#define CONFIG_WITH_BUILD_TIME
#define ROM_BOOT_ADDRESS 1073741824
#define DMA_CHANNELS 1
#define DMA_ADDR_WIDTH 64
#define PCIE_DMA0_READER_INTERRUPT 0
#define PCIE_DMA0_WRITER_INTERRUPT 1
#define CONFIG_CSR_DATA_WIDTH 32
#define CONFIG_CSR_ALIGNMENT 32
#define CONFIG_BUS_STANDARD "WISHBONE"
#define CONFIG_BUS_DATA_WIDTH 32
#define CONFIG_BUS_ADDRESS_WIDTH 32
#define CONFIG_BUS_BURSTING 0
#define TIMER0_INTERRUPT 1
#define UART_INTERRUPT 0
#define CONFIG_HAS_I2C

#endif
